name: Java CI with Maven and SonarCloud in Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    env:
      DOCKER_HOST: unix:///var/run/docker.sock
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin
          cache: maven

      - name: Cache Sonar
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-sonar-

      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Docker check
        run: |
          docker version
          docker info

      - name: Set Maven Additional Goals
        if: ${{ env.SONAR_TOKEN }}
        run: echo "SONARGOAL=sonar:sonar" >> $GITHUB_ENV

      - name: Build with Maven and SonarCloud
        run: >
          xvfb-run -a mvn -B -ntp clean verify -Pjacoco $SONARGOAL
          -Dsonar.organization=perkashlal
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.projectKey=perkashlal_employee-shift
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
